2702 refactor summary table toolbar
kids-first/kf-portal-ui pull request #2703
Opened 2020-09-15 05:19 UTC by francisl

2020-09-15 13:42 UTC, evans-g-crsj requested changes

2020-09-15 13:42 UTC, evans-g-crsj commented on src/components/CohortBuilder/Results.js
>  import { CARDINALITY_PRECISION_THRESHOLD } from '../../common/constants';
../../common vs comon/

2020-09-15 13:42 UTC, evans-g-crsj commented on src/components/CohortBuilder/Results/Toolbar/Toolbar.tsx
> +import { roundIntToChosenPowerOfTen } from '../../../../utils';
../../

2020-09-15 13:42 UTC, evans-g-crsj commented on src/components/CohortBuilder/Results/Toolbar/Toolbar.tsx
> +    //<FilesIcon style={{ marginRight: '6px' }} /> {'No File'}
is this comment necessary?

2020-09-16 13:12 UTC, evans-g-crsj approved these changes

2020-09-16 16:45 UTC, adipaul1981 approved these changes

2020-09-16 20:09 UTC, merged