fix(card_Css): #2732 fix ant card css
kids-first/kf-portal-ui pull request #2751
Opened 2020-09-29 18:54 UTC by adipaul1981

2020-09-29 18:59 UTC, evans-g-crsj approved these changes

2020-09-29 19:34 UTC, francisl requested changes

2020-09-29 19:34 UTC, francisl commented on src/components/UserDashboard/UserDashboard.scss
> +    font-family: 'Open Sans';
theme <-

2020-09-29 19:34 UTC, francisl commented on src/style/dist/themes/default/antd.css
> +  color: #515885;
use color variable. from _colors.less

2020-09-29 19:34 UTC, francisl commented on src/style/dist/themes/default/antd.css
> +  color: #515885;
☝️

2020-09-29 19:34 UTC, francisl commented on src/theme/_vars.scss
> +$greyScale11: #a9adc0;
??? `/theme` is deprecated. Nothing should be added here

2020-09-30 19:27 UTC, francisl approved these changes

2020-09-30 19:27 UTC, merged