Bump version
kids-first/kf-portal-ui pull request #3179
Opened 2021-04-29 20:41 UTC by celinepelletier

2021-04-29 21:32 UTC, francisl commented
Why is there already merged commit in this PR?

2021-04-29 21:33 UTC, francisl requested changes
already merged commit in Pr

2021-04-29 22:48 UTC, celinepelletier commented
This pull request is to merge dev to master (to deploy to prod)

2021-04-30 17:25 UTC, evans-g-crsj approved these changes

2021-04-30 17:28 UTC, merged