fix(reduxdevtool): #SKFP-56 remove redux dev tool in prod
kids-first/kf-portal-ui pull request #3369
Opened 2021-07-22 20:33 UTC by oliviercperrier

2021-07-22 20:46 UTC, evans-g-crsj requested changes

2021-07-22 20:46 UTC, evans-g-crsj commented on src/store/index.js
> -import { composeWithDevTools } from 'redux-devtools-extension/logOnlyInProduction';
I think that it could do the job `'redux-devtools-extension/developmentOnly'`

2021-07-22 21:06 UTC, evans-g-crsj approved these changes

2021-07-23 11:14 UTC, celinepelletier approved these changes

2021-07-26 13:17 UTC, merged