fix(savesets): #3233 fix participant saved sets bug
kids-first/kf-portal-ui pull request #3370
Opened 2021-07-23 20:27 UTC by oliviercperrier

2021-07-24 21:14 UTC, oliviercperrier commented
Did some refactoring at the same time to use hooks in participantTableView

2021-07-26 09:07 UTC, celinepelletier approved these changes

2021-07-26 14:01 UTC, evans-g-crsj requested changes

2021-07-26 14:01 UTC, evans-g-crsj commented on src/components/CohortBuilder/ParticipantsTableView/index.tsx
> +        const dataWithRowSelection = data[0]
a?.b?.c || []

2021-07-26 14:01 UTC, evans-g-crsj commented on src/components/CohortBuilder/ParticipantsTableView/index.tsx
> +            dataTotalCount={data[0] ? data[0].total : 0}
data[0]?total || 0

2021-07-26 14:01 UTC, evans-g-crsj commented on src/components/CohortBuilder/ParticipantsTableView/index.tsx
> +              page: any;
no `any`'s unless you can't do otherwise

2021-07-26 14:10 UTC, oliviercperrier commented on src/components/CohortBuilder/ParticipantsTableView/ParticipantSetDropdown.tsx
> +            fill={exceedLimit() ? '#dd1f2a' : '#a9adc0'}
Its a component rendering an SVG and i'm only using the props exposed. I can't really use a css classe here.

2021-07-26 14:10 UTC, oliviercperrier commented on src/components/CohortBuilder/ParticipantsTableView/ParticipantSetDropdown.scss
> +.ant-dropdown-menu-item:not(.ant-dropdown-menu-item-disabled) {
Was already there, but i can fix it

2021-07-26 15:12 UTC, evans-g-crsj commented on src/components/CohortBuilder/ParticipantsTableView/ParticipantSetDropdown.tsx
> +            fill={exceedLimit() ? '#dd1f2a' : '#a9adc0'}
no probs

2021-08-24 12:10 UTC, celinepelletier commented on src/components/CohortBuilder/Results.js
> +      <div style={{ padding: '0 30px 0 34px' }} className="cb-view-links">
why do you put padding in style here instead of putting in a css class ?

2021-08-24 12:15 UTC, celinepelletier approved these changes

2021-08-31 13:44 UTC, merged