Add keycloak to portal
kids-first/kf-portal-ui pull request #3383
Opened 2021-08-26 21:00 UTC by evans-g-crsj

### DO NOT MERGE

#[BUG | FEATUER | DOC] [TITLE]

- closes [SKFP-9: Add Keycloak authentication in portal](https://d3b.atlassian.net/browse/SKFP-9)

## Description

Acceptance Criterias

## Validation

- [ ] Code Approved
- [ ] Test Coverage
- [x] QA Done
- [x] Design/UI Approved from design

## Screenshot (Before and After)

## QA

https://portal-keycloak-qa.kidsfirstdrc.org/

## Mention

@ QA, Design ...

2021-09-03 18:19 UTC, celinepelletier approved these changes

2021-09-03 19:08 UTC, francisl requested changes
Great Job!
I only have one thing. Absolute import!

We choose to enforce it in kids first since it's considered a best practices in nearly all languages including JS.

Absolute import are : easier to refactor, easier to understand, faster to read, less prone to errors

2021-09-03 19:08 UTC, francisl commented on src/components/UserProfile/HeaderBannerContainer.js
> +import { withApi } from '../../services/api';
☝️

2021-09-03 19:08 UTC, francisl commented on src/components/UserProfile/Settings.js
>  import { SHOW_DELETE_ACCOUNT } from '../../common/constants';
☝️

2021-09-03 19:08 UTC, francisl commented on src/components/UserProfile/UserProfilePageContainer.js
> +import { withApi } from '../../services/api';
☝️

2021-09-03 19:08 UTC, francisl commented on src/pages/variantsSearchPage/Suggester.tsx
> +import { withApi } from '../../services/api';
☝️

2021-09-03 19:08 UTC, francisl commented on src/services/ajax.js
> +import keycloak from '../keycloak';
absolute import

2021-09-03 19:08 UTC, francisl commented on src/services/members/search.js
☝️

2021-09-03 19:56 UTC, celinepelletier commented on src/components/CohortBuilder/VirtualStudiesMenu/LoadQuery.tsx
> +import '../../LoadShareSaveDeleteQuery/LoadShareSaveDeleteQuery.css';
even for css ?

2021-09-08 16:03 UTC, francisl commented on src/components/CohortBuilder/VirtualStudiesMenu/LoadQuery.tsx
> +import '../../LoadShareSaveDeleteQuery/LoadShareSaveDeleteQuery.css';
the good pratice here would be to have a `LoadQuery.css | LoadQuery.module.css | LoadQuery.module.scss` that you load from the source.

if you have to reuse rules, the `module` file should import it

2021-09-10 19:59 UTC, celinepelletier commented on src/components/CohortBuilder/VirtualStudiesMenu/LoadQuery.tsx
> +import '../../LoadShareSaveDeleteQuery/LoadShareSaveDeleteQuery.css';
actually this import is useless, i just remove it

2021-11-03 22:12 UTC, merged